server:
  port: 8801

management.security.enabled: false

spring:
  application:
    name: eureka


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/


#---
#spring:
#  profiles: discovery1
#
#server:
#  port: 8801
#
#eureka:
#  instance:
#    hostname: discovery1
#  client:
#    serviceUrl:
#      defaultZone: http://discovery2:8802/eureka/
#
#---
#spring:
#  profiles: discovery2
#
#server:
#  port: 8802
#
#eureka:
#  instance:
#    hostname: discovery2
#  client:
#    serviceUrl:
#      defaultZone: http://discovery1:8801/eureka/